# Generated by Django 6.0.7 on 2026-08-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='requester_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.bloodrequest')),
            ],
        ),
    ]
