# Generated by Django 6.0.7 on 2026-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_bloodrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='consent_to_disclose',
            field=models.BooleanField(default=True),
        ),
    ]
